from gtts import gTTS

texto = "Mecanismos de resistencia a penicilina de Enterococcus spp. \n" \
        "La ampicilina y la penicilina son los β-lactámicos más activos contra los enterococos que inhiben la síntesis de peptidoglicano, la estructura básica de la pared celular bacteriana y un componente crítico necesario para la viabilidad bacteriana. Como tal, la maquinaria de síntesis y mantenimiento de peptidoglicanos ha sido durante mucho tiempo un objetivo de la terapia antimicrobiana.\n" \
        "Además, la falta de estructuras similares en las células eucariotas disminuye los perfiles de toxicidad de muchos de estos agentes, lo que los convierte en un objetivo ideal contra las bacterias. Proteínas de penicilina-unión (PBP) Es el elemento principal de la pared celular de síntesis y que se pueden dividir en dos grupos: la clase A, que son enzimas bifuncionales que poseen ambos D, D-transpeptidasa y actividad transglicosilasa, y clase B, que poseen solo el dominio transpeptidasa y dependen de la actividad transglicosilasa de otras enzimas. El desarrollo de resistencia a la penicilina en enterococos se ha asociado con la sobreproducción de una proteína de unión a la penicilina (PBP) de baja afinidad que es un componente normal del patrón PBP de estas bacterias y aparentemente es capaz de sustituir las funciones de las otras PBP.\n" \
        "La variación de la secuencia de PBP5 es suficiente para distinguir dos grupos de E. faecium , uno que posee un alto nivel de resistencia a la ampicilina (denominado Pbp5-R) asociado con el entorno hospitalario y una variante asociada a la comunidad (Pbp5-S) que da como resultado CMI más bajas para ampicilina, pero no puede explicar completamente los diferentes perfiles de susceptibilidad observados en la práctica clínica. Por tanto, factores aún no identificados juegan un papel importante en la expresión de resistencia a través de Pbp5 en E. faecium . En E. faecalis, pbp5 parece existir independientemente de la estructura del operón descrita en E. faecium, y aunque también codifica una PBP de clase B, tiene una tolerancia intrínseca más baja a la ampicilina. \n" \
        "La hipersusceptibilidad a la penicilina se asoció con una mutación puntual en el gen pbp5, que causa la terminación prematura de la traducción. Se han sugerido homologías estructurales entre PBP de baja afinidad de las diferentes especies enterocócicas mediante la reactividad cruzada de los anticuerpos elevados contra E. hirae PBP5 con PBP5 de Enterococcus faecium y Enterococcus faecalis. Adquisición de una resistencia a la ampicilina de alto nivel en E. faecium se asoció con la sobreproducción de PBP5, que, en comparación con la PBP5 de cepas moderadamente resistentes, parecía estar modificada en su capacidad de unión a la penicilina. \n" \
        "Se encontró que el fenotipo modificado de PBP5 estaba asociado a algunas sustituciones de aminoácidos en la región entre los motivos SDN y KTG. En particular, la sustitución que convierte un residuo polar (T) en uno no polar (A o I) podría desempeñar un papel importante en la remodelación del dominio de unión a la penicilina y la determinación de la disminución de la afinidad de la penicilina.\n" \
        "Los genes PBP de aislados resistentes a la penicilina son muy variables y tienen una estructura mosaica compuesta por bloques de nucleótidos que son similares a los que se encuentran en los genes PBP de aislados sensibles a la penicilina y bloques que difieren hasta en un 21 %. Estos genes de mosaico codificados cromosómicamente presumiblemente han surgido después de la transformación y la recombinación homóloga con genes PBP de una serie de especies estrechamente relacionadas.\n" \
        "Otra forma de resistencia a la ampicilina, mediada por una β-lactamasa que inactiva el antibiótico mediante la escisión del anillo β-lactámico, se ha descrito tanto en E. faecalis como en E. faecium. Originalmente descrito en estafilococos, el gen blaZ codifica una β-lactamasa como parte de un operón con blaR1, un sensor transmembrana y transductor de señal, y blaI, un gen represor.\n" \
        "A diferencia de los estafilococos, blaZ en los enterococos se expresa de forma constitutiva y en un nivel mucho más bajo, lo que da como resultado un efecto de inóculo clínicamente significativo. Por lo tanto, cuando se inoculan bacterias en concentraciones para las pruebas de susceptibilidad de rutina, los enterococos producen tan poca enzima que resultan susceptibles, mientras que, con un inóculo alto, como durante la infección, la presencia de más enzima conduce a resistencia.\n"
tts = gTTS(text=texto, lang="es", slow=False, tld='com.mx')
tts.save("andrea.mp3")

